# Server Configuration
server:
  port: 8080              # The port your application will run on
  servlet:
    context-path: /api    # Base URL path for your application

# DataSource Configuration
spring:
  profiles:
    active: dev           # Set the active profile (dev, test, prod)
  datasource:
    url: jdbc:postgresql://localhost:5432/library  # Replace with your database name
    username: library                              # Replace with your username
    password: library-api-password-24                              # Replace with your password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update     # Use 'update' for development; use 'validate' or 'none' in production
    show-sql: true         # Print SQL queries to the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging:
  level:
    root: info             # Set root logging level
    org.springframework: debug # Debug logging for Spring
